### ISSUE TITLE
[BUG] createArticle requests always fail.

### ISSUE THREAD

**Issue by nikaera** [khaosdoctor/devto-nodejs-sdk#5]
**Describe the bug**
[`createArticle` function](https://github.com/khaosdoctor/devto-nodejs-sdk/blob/master/src/repositories/ThePracticalDevClient.ts#L41) fails no matter what parameter is set.

**To Reproduce**
1. Set only title and bodyMarkdown when using the `createArticle` function.
2. Set the field values very simply `{ title: "Title", bodyMarkdown: "Body"}`.

**Current behavior**
The following error always occurs every time. This is because the parameter for `POST /articles` is set to `bodyMarkdown` instead of `body_markdown`.
```
error: 'Body markdown is too short (minimum is 0 characters)',
status: 422
```

**Expected behavior**
I would like to run successfully and create an article in dev.to.

**Screenshots**

**Additional context**

I already know the cause of this issue. 🙋 Each field is defined as a camel case, and we need to make it a snake case when executing API requests, but since it is still a camel case, it doesn't seem to be accepting the requests correctly. ✅ I modified Axios to convert all field names to snake case using the following library where it was executing the HTTP request, and confirmed that the request was successfully executed. 🐍 
https://github.com/mpyw/axios-case-converter

The actual modification is as follows, but if it's OK, I'd like to submit a PR. ⚒️ 
https://github.com/nikaera/devto-nodejs-sdk/commit/2800284f47e57960946edda601942ae4c6aa1649

Thank you for creating a great library! 🙇

**Comment by khaosdoctor** [comment]
Hi @nikaera! First of all, thanks a lot for submitting this issue. I found your solution very simple e very elegant. If you could please open a PR, I'd be glad to review it!

**Comment by nikaera** [comment]
Hi @khaosdoctor! I have created a PR.😎  Thank you for your review! 🙋‍♂️ 
https://github.com/khaosdoctor/devto-nodejs-sdk/pull/6
